version: "1.0"
services: 
  partytime-database:
    container_name: mysql-db
    image: mysql
    volumes: 
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "partyDB"
      MYSQL_BIND_ADDRESS: "0.0.0.0"
    ports: 
      - "3306:3306"
    expose:
      - "3306"
