[client]
showErrorDetails = false
toolbarMode = "minimal"

[runner]
fastReruns = true

[server]
baseUrlPath = "party-time"
port = 8080
sslCertFile = "./certificates/fullchain.pem"
sslKeyFile = "./certificates/privkey.key"

[theme]
base="dark"
